'use client';
import { useRef, useState } from 'react';
import { ArrowUpRight, Check, Download, ExternalLink, Heart, LockKeyhole, RefreshCw, ShieldCheck, Trash2, Upload } from 'lucide-react';
import { Journal, Player } from '@/lib/model';
import type { SyncState } from '@/lib/cloud-repository';
import { Tile } from './ui';
function PlayerProfile({ player, onSave }: { player: Player; onSave: (player: Player, original?: Player) => Promise<void> }) {
  const [editing, setEditing] = useState(false);
  const [original, setOriginal] = useState(player);
  const [naspa, setNaspa] = useState(player.naspaRating?.toString() ?? '');
  const [wgpo, setWgpo] = useState(player.wgpoRating?.toString() ?? '');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  return <article className={`card player-profile ${player.id}`}><div className="profile-heading"><Tile letter={player.id === 'ben' ? 'B' : 'S'} points={player.id === 'ben' ? 3 : 1} /><div><span className="eyebrow">YOUR PLAYER PROFILE</span><h2>{player.name}</h2></div><span className="profile-number">{player.id === 'ben' ? '01' : '02'}</span></div>
    <div className="profile-ratings"><div><span>NASPA / NWL</span><strong>{player.naspaRating ?? '—'}</strong></div><div><span>WGPO</span><strong>{player.wgpoRating ?? '—'}</strong></div></div>
    <p className="rating-updated">Last updated: {player.ratingsLastUpdated ? new Date(player.ratingsLastUpdated).toLocaleString() : 'Not yet'}{player.ratingSource === 'manual' && ' · Manual entry'}</p>
    <div className="profile-actions"><div className="profile-record-links"><a href={player.crossTablesUrl} target="_blank" rel="noreferrer">Cross-Tables profile <ExternalLink size={13} /></a><a href={`https://www.cross-tables.com/daddy.php?p=${player.id === 'ben' ? '15872' : '22923'}`} target="_blank" rel="noreferrer">Head to Head record <ExternalLink size={13} /></a></div><button className="text-button" onClick={() => { setNaspa(player.naspaRating?.toString() ?? ''); setWgpo(player.wgpoRating?.toString() ?? ''); setError(''); setOriginal(player); setEditing(!editing); }}>{editing ? 'Cancel' : 'Enter ratings manually'}</button></div>
    {editing && <form className="manual-ratings" onSubmit={async event => { event.preventDefault(); setBusy(true); setError(''); try { for (const value of [naspa, wgpo]) { if (value !== '' && (!Number.isInteger(Number(value)) || Number(value) < 0 || Number(value) > 4000)) throw new Error('Ratings must be whole numbers from 0 to 4,000.'); } await onSave({ ...player, naspaRating: naspa === '' ? null : Number(naspa), wgpoRating: wgpo === '' ? null : Number(wgpo), ratingsLastUpdated: new Date().toISOString(), ratingSource: 'manual' }, original); setEditing(false); } catch (err) { setError(err instanceof Error ? err.message : 'Could not save ratings.'); } finally { setBusy(false); } }}><div className="form-row"><label className="field">NASPA / NWL<input aria-label={`${player.name} NASPA rating`} type="number" inputMode="numeric" min={0} max={4000} step={1} value={naspa} onChange={e => setNaspa(e.target.value)} /></label><label className="field">WGPO<input aria-label={`${player.name} WGPO rating`} type="number" inputMode="numeric" min={0} max={4000} step={1} value={wgpo} onChange={e => setWgpo(e.target.value)} /></label></div>{error && <p className="error-message" role="alert">{error}</p>}<button className="button secondary" disabled={busy}><Check size={16} />Save {player.name}’s ratings</button></form>}
  </article>;
}
export function MoreView({ journal, onSavePlayer, onExport, onImport, onRemoveSamples, onRatings, ratingsBusy, ratingsMessage, cloud = false, syncState, accountName, onSignOut, localGameCount = 0, onImportLocal }: { cloud?: boolean; syncState?: SyncState; accountName?: string; onSignOut?: () => Promise<void>; localGameCount?: number; onImportLocal?: () => void; journal: Journal; onSavePlayer: (player: Player, original?: Player) => Promise<void>; onExport: () => void; onImport: (file: File) => Promise<void>; onRemoveSamples: () => void; onRatings: () => void; ratingsBusy: boolean; ratingsMessage: string }) {
  const input = useRef<HTMLInputElement>(null);
  const sampleCount = journal.games.filter(g => g.isSample).length;
  return <>
    {cloud && <section className="card shared-account"><span className="eyebrow">OUR SHARED JOURNAL</span><h2>Signed in as {accountName}</h2><p>{syncState === 'live' ? 'Connected. Games and photos update on both phones.' : 'Connecting to your shared journal. Changes need an internet connection.'}</p><button className="text-button" onClick={() => void onSignOut?.()}>Sign out on this device</button>{localGameCount > 0 && onImportLocal && <div className="local-import"><p>This phone has {localGameCount} saved games from your original journal. Review and import them into your shared journal. The original stays on this phone.</p><button className="button secondary" onClick={onImportLocal}><Upload size={16} />Import this phone’s saved games</button></div>}</section>}
    <div className="section-heading ratings-heading"><div><span className="eyebrow">TWO PLAYERS. ONE JOURNAL.</span><h2>The people behind the tiles</h2></div><button className="button secondary" onClick={onRatings} disabled={ratingsBusy}><RefreshCw size={16} className={ratingsBusy ? 'spin' : ''} />{ratingsBusy ? 'Checking ratings…' : 'Update ratings'}</button></div>
    <div className="profiles-grid">{journal.players.map(p => <PlayerProfile key={p.id} player={p} onSave={onSavePlayer} />)}</div>
    <div className={`ratings-notice ${ratingsMessage ? 'has-message' : ''}`} role="status"><ShieldCheck size={18} /><p>{ratingsMessage || 'Ratings are supplementary. Cross-Tables is checked on the server, with a daily cache. If a refresh fails, your saved ratings stay safe. Manual ratings work anytime.'}</p></div>
    <section className="card data-card"><div className="section-heading"><div><span className="eyebrow">KEEP YOUR MEMORIES SAFE</span><h2>Your journal, in your hands</h2></div><LockKeyhole size={22} /></div><p>{cloud ? 'Your games and photos are stored privately in your shared journal. Export a backup whenever you want a portable copy.' : 'Your games and photos live in this browser on this device. Export a backup regularly — especially before clearing browser data or changing phones.'}</p><div className="backup-actions"><button className="backup-button" onClick={onExport}><span className="backup-icon"><Download size={23} /></span><span><strong>Export data</strong><small>All games, profiles & photos as JSON</small></span><ArrowUpRight size={18} /></button><button className="backup-button" onClick={() => input.current?.click()}><span className="backup-icon"><Upload size={23} /></span><span><strong>Import data</strong><small>Validate and review a saved backup</small></span><ArrowUpRight size={18} /></button><input ref={input} hidden type="file" accept=".json,application/json" aria-label="Import JSON backup" onChange={event => { const file = event.target.files?.[0]; if (file) void onImport(file); event.target.value = ''; }} /></div><div className="data-status"><span className="status-dot" />{journal.games.filter(g => !g.isSample).length} real games · {sampleCount} sample games · {cloud ? 'Shared cloud storage' : 'Local storage'}</div></section>
    {sampleCount > 0 && <section className="sample-management"><div><span className="eyebrow">A LITTLE INSPIRATION, NOT YOUR HISTORY</span><h3>Ready to make it your own?</h3><p>Remove all {sampleCount} sample games. Your real games and profiles will stay.</p></div><button className="button secondary" onClick={onRemoveSamples}><Trash2 size={16} />Delete sample data</button></section>}
    <section className="about-card"><div className="about-symbol"><Heart size={22} /></div><div><h2>Anniversary Series</h2><p>A little friendly rivalry. A place for the words, the wins, and the evenings together. Made for Ben & Sharon.</p><p className="muted">{cloud ? 'Version 2 · Private shared journal' : 'Version 1 · Local-first · No account needed'}<br />An independent personal journal, not affiliated with Scrabble or its owners.</p><details className="about-details"><summary>Using it on your phones & what comes next</summary><p>Use your browser’s “Add to Home Screen” on an HTTPS deployment. Once visited online, the app caches its pages for basic offline use. {cloud ? 'Sign in on both phones to share your journal. An internet connection is needed to load and save shared games.' : 'Both phones currently keep separate journals; export and import to transfer a copy.'}</p><p>{cloud ? 'Changes appear on the other phone automatically while the app is open, and refresh when you return. If both phones edit the same game at once, review the newer version before saving again.' : 'Configure the private Supabase household to enable shared games, photos, and invited email accounts.'}</p></details></div></section>
  </>;
}
