'use client';
import { Flame, Heart, Sparkles, Trophy } from 'lucide-react';
import { formatDate, Game, margin, newestFirst, winner } from '@/lib/model';
import { milestones, record, statistics } from '@/lib/statistics';
import { EmptyState, number } from './ui';
function RecordLine({ label, value }: { label: string; value: ReturnType<typeof record> }) {
  return <div className="record-line"><span>{label}<small>{value.total} games</small></span><strong><span>{value.ben}</span><i>–</i><span className="green">{value.sharon}</span><small>{value.ties} {value.ties === 1 ? 'tie' : 'ties'}</small></strong></div>;
}
export function StatisticsView({ games, onOpen }: { games: Game[]; onOpen: (game: Game) => void }) {
  const s = statistics(games);
  const m = milestones(games);
  const recent = [...games].sort(newestFirst).slice(0, 10);
  const winPercent = (wins: number) => s.record.total ? `${number(100 * wins / s.record.total, 1)}%` : '—';
  const open = (g: Game | null) => { if (g) onOpen(g); };
  if (!games.length) return <section className="card"><EmptyState title="Good stories need a first chapter." text="Your statistics and milestones will grow automatically as you record games." /></section>;
  return <>
    <section className="stats-overview"><div><span className="eyebrow">THE BIG PICTURE</span><h2>{games.length} games.<br />One ongoing rivalry.</h2><p>Every score adds a little to your story.</p></div><div className="stat-win"><span>BEN WINS</span><strong>{s.record.ben}</strong><small>{winPercent(s.record.ben)} of all games</small></div><div className="stat-win green"><span>SHARON WINS</span><strong>{s.record.sharon}</strong><small>{winPercent(s.record.sharon)} of all games</small></div><div className="stat-win tie"><span>TIES</span><strong>{s.record.ties}</strong><small>Sharing the honours</small></div></section>
    <div className="stats-grid"><section className="card stats-card"><div className="section-heading"><h2>The numbers game</h2><Trophy size={19} /></div><table className="scores-table"><thead><tr><th>Scoring</th><th>Ben</th><th>Sharon</th></tr></thead><tbody><tr><td>Average score</td><td>{number(s.ben.average, 1)}</td><td>{number(s.sharon.average, 1)}</td></tr><tr><td>Highest score</td><td>{number(s.ben.high)}</td><td>{number(s.sharon.high)}</td></tr><tr><td>Lowest score</td><td>{number(s.ben.low)}</td><td>{number(s.sharon.low)}</td></tr><tr><td>Longest win streak</td><td>{s.longest.ben}</td><td>{s.longest.sharon}</td></tr></tbody></table><div className="table-footer"><span>Average combined score</span><strong>{number(s.combinedAverage, 1)}</strong></div></section>
      <section className="card stats-card"><div className="section-heading"><h2>It’s a close game</h2><Heart size={19} /></div><div className="stat-list"><div><span>Average winning margin<small>Ties excluded</small></span><strong>{number(s.averageMargin, 1)} <small>pts</small></strong></div><button onClick={() => open(s.closest)}><span>Closest game<small>{s.closest ? formatDate(s.closest.date) : 'No games yet'}</small></span><strong>{s.closest ? margin(s.closest) : '—'} <small>pts</small></strong></button><button onClick={() => open(s.biggestBen)} disabled={!s.biggestBen}><span>Biggest Ben win</span><strong>{s.biggestBen ? margin(s.biggestBen) : '—'} <small>pts</small></strong></button><button onClick={() => open(s.biggestSharon)} disabled={!s.biggestSharon}><span>Biggest Sharon win</span><strong>{s.biggestSharon ? margin(s.biggestSharon) : '—'} <small>pts</small></strong></button></div></section>
      <section className="card stats-card"><div className="section-heading"><h2>A little momentum</h2><Flame size={19} /></div><div className="recent-form"><span className="eyebrow">LAST {recent.length} GAMES · NEWEST FIRST</span><div className="form-dots">{recent.map(g => <button key={g.id} className={`form-dot ${winner(g)}`} onClick={() => onOpen(g)} aria-label={`${formatDate(g.date)}: ${winner(g) === 'tie' ? 'tie' : `${winner(g)} wins`}`}>{winner(g) === 'tie' ? '=' : winner(g) === 'ben' ? 'B' : 'S'}</button>)}</div></div><RecordLine label="Last 5 games" value={s.last5} /><RecordLine label="Last 10 games" value={s.last10} /><div className="table-footer"><span>Current winning streak</span><strong>{s.currentStreak.player ? `${s.currentStreak.player === 'ben' ? 'Ben' : 'Sharon'} · ${s.currentStreak.count}` : 'No current streak'}</strong></div></section>
      <section className="card stats-card"><div className="section-heading"><h2>The finer details</h2><Sparkles size={19} /></div><div className="stat-list"><div><span>Highest combined score</span><strong>{s.combinedHigh}</strong></div><div><span>Lowest combined score</span><strong>{s.combinedLow}</strong></div><div><span>Average Ben − Sharon difference</span><strong>{number(s.averageDifference, 1)}</strong></div><div><span>Most common margin<small>{s.commonMarginFrequency} occurrences each</small></span><strong className="common-margins">{s.commonMargins.length > 4 ? `${s.commonMargins.length} equally common margins` : s.commonMargins.join(', ')}<small>{s.commonMargins.length <= 4 ? ' pts' : ''}</small></strong></div></div></section>
    </div>
    <section className="card trends-card"><div className="section-heading"><h2>Where the words take you</h2><span className="muted">Records shown as Ben – Sharon, with ties</span></div><div className="trend-columns"><div><span className="eyebrow">BY TIME</span><RecordLine label="This month" value={s.month} /><RecordLine label="This year" value={s.year} /></div><div><span className="eyebrow">BY LOCATION</span>{s.byLocation.map(r => <RecordLine key={r.label} label={r.label} value={r} />)}</div><div><span className="eyebrow">BY GAME TYPE</span>{s.byType.map(r => <RecordLine key={r.label} label={r.label} value={r} />)}</div></div></section>
    <section className="milestones-section"><div className="section-heading"><div><span className="eyebrow">LITTLE THINGS, BIG MEMORIES</span><h2>Worth celebrating</h2></div><Sparkles size={22} /></div><div className="milestone-grid">{m.map((item, i) => <button className="milestone-card" key={`${item.title}-${i}`} onClick={() => { const g = games.find(g => g.id === item.gameId); if (g) onOpen(g); }}><span className="milestone-icon">{item.kind === 'heart' ? <Heart size={22} /> : item.kind === 'trophy' ? <Trophy size={22} /> : <Sparkles size={22} />}</span><strong>{item.title}</strong><p>{item.description}</p></button>)}</div><p className="form-footnote">Only milestones your recorded scores can prove. Comebacks need turn-by-turn scores, so they’re saved for later.</p></section>
  </>;
}
